Repository RisedSky/discordPandaJS, pull requests merged in 2018-03, with the labels that each got.

#13 Correction
  ISSUE_TEMPLATE.md
Labels: Enhancement

#15 Merge
  discordPanda.js
Labels: Done ✓

#16 Check if it's an instant purge or not (exemple 0)
  discordPanda.js
Labels: Enhancement, P2

#18 Distribution 1.0
  discordPanda.js
  whitelistServer.js
Labels: Enhancement, Will be pushed soon

#19 Added the pause command & changed music function
  discordPanda.js
Labels: Enhancement, P3

#20 Little changes
  discordPanda.js
Labels: Enhancement, P3

#21 La commande purge fonctionne malgré le tag <nocmds>
  discordPanda.js
Labels: Enhancement, Will be pushed soon

#23 Added a new purge cmd
  discordPanda.js
Labels: Enhancement, P1

#24 Commandes *servers
  discordPanda.js
Labels: Enhancement, P3

#25 Update README.md
  README.md
Labels: Enhancement, P3

#26 Verify if the user is in the same vocal as me
  discordPanda.js
Labels: Enhancement, P2

#27 Little changes
  discordPanda.js
Labels: Enhancement, P2

#28 A variable wasn't written correctly, i changed it.
  discordPanda.js
Labels: P1

#29 Server link fix
  discordPanda.js
Labels: Bug, Done ✓

#30 Some changes
  discordPanda.js
Labels: Enhancement

#32 Some changes (feature, function, code arrangment and more)
  discordPanda.js
Labels: Enhancement, P3

#33 Reaction catch error
  discordPanda.js
Labels: Bug, P1, Urgent

#34 Changed the random-member answer, to prevent spam abusing
  discordPanda.js
Labels: Enhancement, P1, Will be pushed soon

#35 Rekt command changes
  discordPanda.js
Labels: Enhancement, P1, Urgent

#36 Added the mysql, purge command fix and much more !
  config.js
  discordPanda.js
  package.json
Labels: Enhancement, Will be pushed soon

#39 Update README.md
  README.md
Labels: Enhancement
